### ISSUE TITLE
(0, e.nullToValuye) is not a function

### ISSUE THREAD

**Issue by ghaushe-ampere** [a270443177/vxiaobai-timeseries-panel#1]
When trying to use this plugin with Grafana 10.3.7, I get this error:
![image](https://github.com/user-attachments/assets/ede7d36b-f0e5-49f1-805d-2d9d56cceffc)

**Comment by a270443177** [comment]
> When trying to use this plugin with Grafana 10.3.7, I get this error: ![image](https://private-user-images.githubusercontent.com/134623708/392073689-ede7d36b-f0e5-49f1-805d-2d9d56cceffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTI2OTIsIm5iZiI6MTczMzI5MjM5MiwicGF0aCI6Ii8xMzQ2MjM3MDgvMzkyMDczNjg5LWVkZTdkMzZiLWYwZTUtNDlmMS04MDVkLTJkOWQ1NmNjZWZmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwNjA2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Njc4NDk4ZjQ2ZjUzMWIxZDEwZGNkMjliMDA3YmM2YTgzZDA1YTYzMzNlNTEzNmY4MGY2N2RjODA5ZTBhNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jud7A8KAuWG1PlPGgUgNmAR7w63eKwOHAE2K7qKZ3c8)

sorry   only test in 10.4.2

**Comment by a270443177** [comment]
增加10.3.7版本的支持
